[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dash-tailwindcss-plugin"
version = "0.1.2"
description = "A Dash plugin for integrating TailwindCSS using Dash 3.x hooks"
readme = "README.md"
requires-python = ">=3.8"
authors = [{name = "insistence", email = "3055204202@qq.com"}]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Framework :: Dash",
]
dependencies = [
    "dash>=3.0.3",
]

[project.urls]
Homepage = "https://github.com/HogaStack/dash-tailwindcss-plugin"
Documentation = "https://github.com/HogaStack/dash-tailwindcss-plugin"
Repository = "https://github.com/HogaStack/dash-tailwindcss-plugin"
Issues = "https://github.com/HogaStack/dash-tailwindcss-plugin/issues"

[project.optional-dependencies]
dev = ["build", "twine"]
test = ["pytest>=6.0"]

[project.scripts]
dash-tailwindcss-plugin = "dash_tailwindcss_plugin.cli:main"

[tool.setuptools]
packages = ["dash_tailwindcss_plugin"]